version: '3.1'

services:

  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp-user
      WORDPRESS_DB_PASSWORD: wp-pass
      WORDPRESS_DB_NAME: wp_db
    volumes:
      - ${WP_PLUGIN_SRC}:/var/www/html/wp-content/plugins/uvic-captions-player

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wp_db
      MYSQL_USER: wp-user
      MYSQL_PASSWORD: wp-pass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ${WP_MYSQL_DIR}:/var/lib/mysql